### ISSUE TITLE
have a way to deploy only one overlay from Pull Request

### ISSUE THREAD

**Issue by pacospace** [AICoE/aicoe-ci#125]
**Is your feature request related to a problem? Please describe.**
As Developer,

I have 10 overlays and I open a feature only for one of them, I don't want to create images from PR for all overlays but only for one.

**Describe the solution you'd like**
Alllow user to have `/deploy {overlay-name}`

**Describe alternatives you've considered**

**Additional context**
after discussion with @harshad16

**Comment by Gregory-Pereira** [comment]
Could we use a .dockerignore file ([see example](https://codefresh.io/docker-tutorial/not-ignore-dockerignore-2/)) to scope what you are building, allowing for you to create the image for only the features that you are targeting? The problem is that this may become difficult to maintain if multiple people are merging specific features and are not sure what should be included or not included, so some other part would be required to call this a solution. What do you think?
