### ISSUE TITLE
Help with Sesheta invite

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [AICoE/aicoe-ci#181]
### GitHub Repo

https://github.com/os-climate/essd-ingest-pipeline/

**Comment by harshad16** [comment]
@MichaelTiemannOSC  please send a request to user https://github.com/sesheta for this repo.
we this issue will look for the invite and accept it.

**Comment by MichaelTiemannOSC** [comment]
I'm sorry, but I don't understand what is means to "send a request to [a] user".  I know how to file issues, make pull requests, assign resources and labels, etc.  But not how to send a request.

**Comment by harshad16** [comment]
That alright , i can help you with this
before we invite the sesheta to be the contributor
can you please confirm, this is in regards with image build for the repo? or is it regarding something else?

**Comment by MichaelTiemannOSC** [comment]
I want to be able to put an image on Quay that can be used for automating notebook pipelines.  Vincent Caldeira has suggested that I really should be building images to run in Airflow, not Elyra, if that matters.  But in any case, it will be something derived from an AICoE Dockerfile, with python module dependencies appropriate for use in OS-Climate.

**Comment by harshad16** [comment]
ack, 
sesheta is already a member of os-climate org.
For the build process, now we are just missing build details:
- base image: based on what is needed 
- build-strategy: s2i or Dockerfile
- quay repo: where to push the image on quay after build.


Base image:
As you said airflow could be something that you would like to use, we dont have any image for airflow , so that would be upto which base image to use.
if you would like something based on **elyra** use: `quay.io/thoth-station/s2i-elyra-custom-notebook:latest`
Update this value with the selected base image: https://github.com/os-climate/essd-ingest-pipeline/blob/6a9cfc512097e5678c2e9b66d8bb46a83754497d/.aicoe-ci.yaml#L10


Build strategy:
[s2i](https://github.com/openshift/source-to-image) and dockerfile both are allowed.
Update this value with the selected option: https://github.com/os-climate/essd-ingest-pipeline/blob/6a9cfc512097e5678c2e9b66d8bb46a83754497d/.aicoe-ci.yaml#L8
If prefered dockerfile switch with these line: https://github.com/AICoE/aicoe-ci/blob/master/docs/.aicoe-ci.yaml#L11-L12

Quay repo:
you would have to create a repo in os-climate quay org.  like this https://quay.io/repository/os-climate/aicoe-osc-demo?tab=tags
in the setting of the repo, you would have to select the **os-climate-pusher** bot from dropdown under the section robot premission with **write** access
and update the https://github.com/os-climate/essd-ingest-pipeline/blob/master/.aicoe-ci.yaml#L11-L14 similar to https://github.com/os-climate/aicoe-osc-demo/blob/master/.aicoe-ci.yaml#L11-L14


Line https://github.com/os-climate/essd-ingest-pipeline/blob/6a9cfc512097e5678c2e9b66d8bb46a83754497d/.aicoe-ci.yaml#L9 can be removed it is if user want to run custom script when using s2i. 
After these setting , all is set for custom build on each github tag creation.
