### ISSUE TITLE
Tag release failing to build for workflow-helpers but no logs available

### ISSUE THREAD

**Issue by pacospace** [AICoE/aicoe-ci#57]
**Describe the bug**
I would like to know why build failed

**To Reproduce**
1. Create git tag in repo and look at Tekton Pipeline Run
2. Go to logs for build Task

**Expected behavior**
Build is successful and new image is available on Quay

**Screenshots**

**Additional context**

**Comment by harshad16** [comment]
The issue pipeline failed to build tag for workflow-helper is due to the mis-match of python version, the pipeline was not able to build the python 3.6(stated in [Pipfile](https://github.com/thoth-station/workflow-helpers/blob/afa74b622e6da5bf4b47cf45eb071aba8a80699c/Pipfile#L16)) based application in python 3.8 image (stated in [aicoe-ci.yaml](https://github.com/thoth-station/workflow-helpers/blob/afa74b622e6da5bf4b47cf45eb071aba8a80699c/.aicoe-ci.yaml#L5) ). 
checked in new deployment of ocp cluster: https://console-openshift-console.apps.ocp.prod.psi.redhat.com/k8s/ns/aicoe-infra-prod/tekton.dev~v1alpha1~PipelineRun/tag-release-24hbr/logs
fix for this would be sent in.

Apart from this will open a feature, such that when a build fails , an issue is opened. so that it can be investigated and worked upon in future.

**Comment by goern** [comment]
can we close this @pacospace

**Comment by pacospace** [comment]
> can we close this @pacospace

Yes thanks!! @harshad16 solved it already! :)
