### ISSUE TITLE
[tag-release-pipeline] Git info env vars not available in built images

### ISSUE THREAD

**Issue by 4n4nd** [AICoE/aicoe-ci#82]
**Describe the bug**
For Jupyterhub image build pipeline, some [Git env vars](https://github.com/AICoE/s2i-custom-notebook/blob/master/s2i/bin/run#L8) are not set.
This results in all directories being called notebook-xxxx 

**Expected behavior**
`GIT_REPO_NAME` should be passed to newly built image as an env variable.

**Comment by harshad16** [comment]
Thanks for opening this issue.

For the internal projects, we had added these env vars in the internal jupyterhub-build-pipeline itself. However, for the aicoe-ci pipelines, it feels this should be optional as this pertains to the specified build image. We will get the changes in , so that users can define the required build env for the container image building.

**Comment by 4n4nd** [comment]
@harshad16 I don't think env vars like `GIT_REPO_NAME` are too specific, this is just git source and the vars can be empty

**Comment by harshad16** [comment]
Agreed on the GIT_REPO_NAME, we had other env vars in the s2i-custom-notebook like GIT_REPO_URL and others https://github.com/AICoE/s2i-custom-notebook/blob/6ed83c97d759fae567c96db1491a1ebb6342b7e5/s2i/bin/run#L22 , would like to keep that optional, should users can define them themselves. 
The git_repo_name would be included in the builds, would work on getting the other through the configuration file.

**Comment by harshad16** [comment]
This issue is completed with: https://github.com/AICoE/aicoe-ci/pull/84
closing this issue.
