### ISSUE TITLE
release missing from pypi.org

### ISSUE THREAD

**Issue by goern** [AICoE/aicoe-ci#83]
**Describe the bug**
The pipeline has failed somewhere, so that the tag-release https://github.com/thoth-station/thamos/tree/v1.5.0 is missing from https://pypi.org/project/thamos/#history

**Comment by harshad16** [comment]
Thanks for the issue, will get the required changes in soon.

**Comment by harshad16** [comment]
This is currently active in the running instance.
User can use this feature through an issue .
The template for the issue is https://github.com/thoth-station/thamos/blob/master/.github/ISSUE_TEMPLATE/deliver_missing_module.md

user can define the tag for which the pypi release is missing in the template issue, based on this pipeline would work towards the release.
Example: 
https://github.com/thoth-station/thamos/issues/639

This information would be shared in the documentation.
